In [148]:
import pandas as pd
import numpy as np
import calendar

In [140]:
df_prov=pd.read_excel('./Datasets/Raw/2021/August.xls',skiprows=14,header=[0,1],sheet_name='Provider Level Data')
df_prov=df_prov.iloc[:,1:-1]
df_prov.head()

  Unnamed: 1_level_0            Unnamed: 2_level_0  \
                Code                        Region
0                  -                             -
1                NaN                           NaN
2                RC9  NHS England East Of England
3                RGT  NHS England East Of England
4              NQ108  NHS England East Of England

                                  Unnamed: 3_level_0  \
                                                Name
0                                            England
1                                                NaN
2        Bedfordshire Hospitals NHS Foundation Trust
3  Cambridge University Hospitals NHS Foundation ...
4                                   Clacton Hospital

                 A&E attendances                                        \
  Type 1 Departments - Major A&E Type 2 Departments - Single Specialty
0                      1341757.0                               39864.0
1                            NaN                                   NaN
2                        15550.0                                   0.0
3                         9117.0                                   0.0
4                            0.0                                   0.0

                                                                      \
  Type 3 Departments - Other A&E/Minor Injury Unit Total attendances
0                                         654346.0         2035967.0
1                                              NaN               NaN
2                                           5086.0           20636.0
3                                           5224.0           14341.0
4                                           2632.0            2632.0

  A&E attendances less than 4 hours from arrival to admission, transfer or discharge  \
                                                      Type 1 Departments - Major A&E
0                                             777084
1                                                NaN
2                                                  -
3                                                  -
4                                                  0

                                         \
  Type 2 Departments - Single Specialty
0                                 32014
1                                   NaN
2                                     -
3                                     -
4                                     0

                                                    ...  \
  Type 3 Departments - Other A&E/Minor Injury Unit  ...
0                                           585840  ...
1                                              NaN  ...
2                                                -  ...
3                                                -  ...
4                                             2629  ...

  Percentage of attendances within 4 hours  \
    Percentage in 4 hours or less (type 2)
0                                 0.975739
1                                      NaN
2                                        -
3                                        -
4                                        -

                                                        Emergency Admissions  \
  Percentage in 4 hours or less (type 3) Emergency Admissions via Type 1 A&E
0                               0.969796                            381911.0
1                                    NaN                                 NaN
2                                      -                              3887.0
3                                      -                              2627.0
4                                0.99886                                 0.0

                                       \
  Emergency Admissions via Type 2 A&E
0                              1325.0
1                                 NaN
2                                 0.0
3                                 0.0
4                                 0.0

                                             \
  Emergency Admissions via Type 3 and 4 A&E
0                                    5555.0
1                                       NaN
2                                       0.0
3                                      49.0
4                                       0.0

                                      \
  Total Emergency Admissions via A&E
0                           388791.0
1                                NaN
2                             3887.0
3                             2676.0
4                                0.0

                                                                           \
  Other Emergency admissions (i.e not via A&E) Total Emergency Admissions
0                                     115095.0                   503886.0
1                                          NaN                        NaN
2                                       1569.0                     5456.0
3                                        566.0                     3242.0
4                                          0.0                        0.0

                                                                            \
  Number of patients spending >4 hours from decision to admit to admission
0                                            96008.0
1                                                NaN
2                                               57.0
3                                              916.0
4                                                3.0


  Number of patients spending >12 hours from decision to admit to admission
0                                             2787.0
1                                                NaN
2                                                0.0
3                                               82.0
4                                                0.0

[5 rows x 27 columns]

In [141]:
df_prov.columns = [
    '_'.join([str(lvl).strip().replace('Unnamed:', '').replace(' - ', '_').strip('_ ')
              for lvl in col if pd.notna(lvl) and 'Unnamed' not in str(lvl)])
    for col in df_prov.columns
]

In [142]:
for column in df_prov.columns:
    if 'Percentage' in column:
        df_prov=df_prov.drop(column,axis=1)

In [143]:
new_cols = [
    'Code', 'Region', 'Name', 
    'Attend_Type1', 'Attend_Type2', 'Attend_Type3', 'Attend_Total',
    'Within4Hr_Type1', 'Within4Hr_Type2', 'Within4Hr_Type3', 'Within4Hr_Total',
    'Over4Hr_Type1', 'Over4Hr_Type2', 'Over4Hr_Type3', 'Over4Hr_Total',
    'Adm_AE_Type1', 'Adm_AE_Type2', 'Adm_AE_Type3', 'Adm_AE_Total',
    'Adm_Other', 'Adm_Total',
    'DecisionToAdm_Wait_4to12Hr', 'DecisionToAdm_Wait_Over12Hr'
]

In [144]:
df_prov.columns=new_cols
df_prov.head()

,Code,Region,Name,Attend_Type1,Attend_Type2,Attend_Type3,Attend_Total,Within4Hr_Type1,Within4Hr_Type2,Within4Hr_Type3,...,Over4Hr_Type3,Over4Hr_Total,Adm_AE_Type1,Adm_AE_Type2,Adm_AE_Type3,Adm_AE_Total,Adm_Other,Adm_Total,DecisionToAdm_Wait_4to12Hr,DecisionToAdm_Wait_Over12Hr
0,-,-,England,1341757.0,39864.0,654346.0,2035967.0,777084,32014,585840,...,18246,416277,381911.0,1325.0,5555.0,388791.0,115095.0,503886.0,96008.0,2787.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,RC9,NHS England East Of England,Bedfordshire Hospitals NHS Foundation Trust,15550.0,0.0,5086.0,20636.0,-,-,-,...,-,-,3887.0,0.0,0.0,3887.0,1569.0,5456.0,57.0,0.0
3,RGT,NHS England East Of England,Cambridge University Hospitals NHS Foundation ...,9117.0,0.0,5224.0,14341.0,-,-,-,...,-,-,2627.0,0.0,49.0,2676.0,566.0,3242.0,916.0,82.0
4,NQ108,NHS England East Of England,Clacton Hospital,0.0,0.0,2632.0,2632.0,0,0,2629,...,3,3,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0

In [145]:
df_prov.dropna(inplace=True)
df_prov.isna().sum()

Code                           0
Region                         0
Name                           0
Attend_Type1                   0
Attend_Type2                   0
Attend_Type3                   0
Attend_Total                   0
Within4Hr_Type1                0
Within4Hr_Type2                0
Within4Hr_Type3                0
Within4Hr_Total                0
Over4Hr_Type1                  0
Over4Hr_Type2                  0
Over4Hr_Type3                  0
Over4Hr_Total                  0
Adm_AE_Type1                   0
Adm_AE_Type2                   0
Adm_AE_Type3                   0
Adm_AE_Total                   0
Adm_Other                      0
Adm_Total                      0
DecisionToAdm_Wait_4to12Hr     0
DecisionToAdm_Wait_Over12Hr    0
dtype: int64

In [147]:
df_prov=df_prov[df_prov['Code']!='-'].reset_index(drop=True)
df_prov

,Code,Region,Name,Attend_Type1,Attend_Type2,Attend_Type3,Attend_Total,Within4Hr_Type1,Within4Hr_Type2,Within4Hr_Type3,...,Over4Hr_Type3,Over4Hr_Total,Adm_AE_Type1,Adm_AE_Type2,Adm_AE_Type3,Adm_AE_Total,Adm_Other,Adm_Total,DecisionToAdm_Wait_4to12Hr,DecisionToAdm_Wait_Over12Hr
0,RC9,NHS England East Of England,Bedfordshire Hospitals NHS Foundation Trust,15550.0,0.0,5086.0,20636.0,-,-,-,...,-,-,3887.0,0.0,0.0,3887.0,1569.0,5456.0,57.0,0.0
1,RGT,NHS England East Of England,Cambridge University Hospitals NHS Foundation ...,9117.0,0.0,5224.0,14341.0,-,-,-,...,-,-,2627.0,0.0,49.0,2676.0,566.0,3242.0,916.0,82.0
2,NQ108,NHS England East Of England,Clacton Hospital,0.0,0.0,2632.0,2632.0,0,0,2629,...,3,3,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0
3,RWH,NHS England East Of England,East And North Hertfordshire NHS Trust,9204.0,0.0,5724.0,14928.0,5232,0,5707,...,17,3989,2735.0,0.0,0.0,2735.0,259.0,2994.0,277.0,0.0
4,RDE,NHS England East Of England,East Suffolk And North Essex NHS Foundation Trust,14909.0,0.0,6013.0,20922.0,10301,0,5964,...,49,4657,4645.0,0.0,227.0,4872.0,1230.0,6102.0,425.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,RA7,NHS England South West,University Hospitals Bristol And Weston NHS Fo...,13998.0,1903.0,0.0,15901.0,8653,1828,0,...,0,5420,3975.0,6.0,0.0,3981.0,571.0,4552.0,1729.0,257.0
206,R0D,NHS England South West,University Hospitals Dorset NHS Foundation Trust,14487.0,1225.0,1373.0,17085.0,-,-,-,...,-,-,4211.0,5.0,0.0,4216.0,1905.0,6121.0,477.0,0.0
207,RK9,NHS England South West,University Hospitals Plymouth NHS Trust,8290.0,140.0,3791.0,12221.0,-,-,-,...,-,-,2526.0,0.0,923.0,3449.0,0.0,3449.0,555.0,91.0
208,AXG,NHS England South West,Wiltshire Health & Care,0.0,0.0,1373.0,1373.0,0,0,1370,...,3,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
209,RA4,NHS England South West,Yeovil District Hospital NHS Foundation Trust,4968.0,0.0,0.0,4968.0,4492,0,0,...,0,476,1913.0,0.0,0.0,1913.0,300.0,2213.0,14.0,0.0